name: fipy_solver_benchmarking_27
channels:
  - conda-forge
  - defaults
dependencies:
  - python[version='>=2.7,<2.8.0a0']
  - mamba
  - numpy
  - scipy
  - matplotlib-base
  - jupyterlab
  - future
  - memory_profiler
  - mpi4py
  - petsc4py
  - mpich
  - mayavi
  - pytrilinos
  - pysparse
  - python_abi=2.7
  - ca-certificates
  - libcxx[version='>=9.0.1']
  - libffi[version='>=3.2.1,<3.3.0a0']
  - openssl[version='>=1.1.1a,<1.1.2a']
  - readline[version='>=8.0,<9.0a0']
  - sqlite[version='>=3.30.1,<4.0a0']
  - tk[version='>=8.6.10,<8.7.0a0']
  - zlib[version='>=1.2.11,<1.3.0a0']
  - traitsui[version='<7.0.0']
  - gmsh[version='<4.0']
  - pip
