simulations: "config/all_permutations.csv"

fipy_url: "https://github.com/usnistgov/fipy.git"

fipy_revs:
# - "62cbf2211"
# - "d8a569e79"
- "fc047b817" # patched "b873c7e3f"
- "21c82d4c3" # patched "2054173bf"
- "cc1eb816c" # patched "36bff3800"
- "6bf1eae87" # patched "2c7ac213b"

size:
  min: 10
  max: 1000000
  steps: 6

suites:
- "petsc"
- "pysparse"
- "no-pysparse"
- "scipy"

restart: "resources/t=300.0.npz"
checkpoint_interval: 1.
totaltime: 301.
view: False

benchmarks:
  binary_phase_field:
    dimension: 2

# - "diffusion"
# - "nucleation"
