fipy_url: "https://github.com/usnistgov/fipy.git"

fipy_revs:
# - "62cbf2211"
# - "d8a569e79"
- "b873c7e3f"
- "2054173bf"
- "36bff3800"
- "2c7ac213b"

size:
  min: 10
  max: 100
#  max: 1e6

suites:
- "petsc"

benchmarks:
- "binary_phase_field"
# - "diffusion"
# - "nucleation"
