fipy_url: "https://github.com/usnistgov/fipy.git"

fipy_revs:
- "2c7ac213"

size:
  min: 10
  max: 100
#  max: 1e6

suites:
- "petsc"

benchmarks:
- "binary_phase_field"
# - "diffusion"
# - "nucleation"
