simulations: "config/all_permutations.csv"

fipy_url: "https://github.com/usnistgov/fipy.git"

fipy_revs:
# - "d8a569e79"
- "371d28468" # patched "62cbf2211"
- "ef3db887e" # patched "b873c7e3f"
- "f715725b4" # patched "2054173bf"
- "742c901e9" # patched "36bff3800"
- "a5f233aa7" # patched "2c7ac213b"

size:
  min: 10
  max: 1000000
  steps: 6

suites:
- "petsc"
- "pysparse"
- "no-pysparse"
- "scipy"

restart: "resources/t=300.0.npz"
checkpoint_interval: 1.
totaltime: 301.
view: False

benchmarks:
  binary_phase_field:
    dimension: 2

# - "diffusion"
# - "nucleation"
